# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-fasjson-client.spec

# add or remove files that should be synced
files_to_sync:
    - python-fasjson-client.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: fasjson-client
# downstream (Fedora) RPM package name
downstream_package_name: python-fasjson-client

srpm_build_deps:
  - poetry

actions: 
    create-archive:
        - "poetry build"
        - "sh -c 'echo dist/fasjson-client-$(poetry version -s).tar.gz'"
    get-current-version:
        - "poetry version -s"

jobs:

  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-35

  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-35

  - job: copr_build
    trigger: release
    metadata:
      targets:
        - fedora-35
      project: fasjson-client