# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: python-fasjson-client.spec

issue_repository: https://github.com/fedora-infra/fasjson-client

# add or remove files that should be synced
files_to_sync:
    - python-fasjson-client.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: fasjson-client
# downstream (Fedora) RPM package name
downstream_package_name: python-fasjson-client
upstream_tag_template: v{version}

srpm_build_deps:
  - curl

actions:
    post-upstream-clone:
        - "curl https://src.fedoraproject.org/rpms/python-fasjson-client/raw/main/f/python-fasjson-client.spec -o python-fasjson-client.spec"
        - "sh -c 'curl -sSL https://install.python-poetry.org | python3 -'"
        - "/builddir/.local/bin/poetry --version"
    create-archive:
        - "/builddir/.local/bin/poetry build -f sdist"
        - "sh -c 'echo dist/fasjson_client-$(/builddir/.local/bin/poetry version -s).tar.gz'"
    get-current-version:
        - "/builddir/.local/bin/poetry version -s"

jobs:
  # upon upstream PRs, perform copr builds
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # upon upstream release, perform copr builds
  - job: copr_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development
      project: fasjson-client

  # upon downstream changes, create a PR upstream with sync'd files from above
  - job: sync_from_downstream
    trigger: commit

  # land upstream release in fedora dist-git - no builds
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  # create an srpm from upstream and submit a scratch build to koji
  - job: production_build
    trigger: release
    metadata:
      targets:
        - fedora-latest-stable
        - fedora-development

  # downstream automation

  # trigger a build in koji for a new dist-git commit
  - job: koji_build
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development

  # create a new update in bodhi for a successful koji build. directly related to `koji_build`
  - job: bodhi_update
    trigger: commit
    metadata:
      dist_git_branches:
        - fedora-latest-stable
        - fedora-development
