- hosts: localhost
  vars:
    config_path: "{{ playbook_dir }}/../openapi/config.yaml" 
    src_dir: "{{ playbook_dir }}/../../fasjsonclient"
    trash_files:
      - .openapi-generator-ignore
      - .travis.yml
      - openapi_client_README.md
      - .openapi-generator
      - .gitignore
  tasks:
    - name: Generate files
      openapi_gen:
        kind: python
        spec: "{{ openapi_spec_path }}"
        config: "{{ config_path }}"
        dest: "{{ src_dir }}"
      # shell: "openapi-generator-cli \
      #   generate \
      #   -g python \
      #   -i {{ openapi_spec_path }} \
      #   -c {{ config_path }} \
      #   -o {{ src_dir }}"

    - name: Delete unwanted files
      file:
        path: "{{ src_dir }}/{{ item }}"
        state: absent
      with_items: "{{ trash_files }}"