# coding: utf-8

"""
    Fedora Account Service JSON API

    fajson rest api  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_group_members(self):
        """Test case for get_group_members

        """
        pass

    def test_get_user_info(self):
        """Test case for get_user_info

        """
        pass

    def test_query_groups(self):
        """Test case for query_groups

        """
        pass

    def test_whoami(self):
        """Test case for whoami

        """
        pass


if __name__ == '__main__':
    unittest.main()
